source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Welio' do
    pod 'Alamofire', '~> 4.0'
    pod 'KRProgressHUD'
    pod 'Kingfisher', '~> 3.0'
    pod 'SwiftyJSON'
    pod 'Cosmos'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ReachabilitySwift'
    pod 'RealmSwift'
end
